name: Build All

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string

jobs:
  build-lnx:
    uses: ./.github/workflows/build-linux.yml
    with:
      build-type: ${{ inputs.build-type }}
  build-win:
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: ${{ inputs.build-type }}