name: Create Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-all.yml
    with:
      build-type: "Release"
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Version
        run: echo VERSION=`cat version.txt` >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Create and Upload Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.VERSION }}
          makeLatest: true
          omitBody: true
          artifacts: |
            ${{ github.workspace }}/Chip8Emu-linux/Chip8Emu
            ${{ github.workspace }}/Chip8Emu-windows/Chip8Emu.exe
